server:
  port: 9090

# mysql configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #local username of databse
    password: ZJJ201225zjj #password of local database
    url: jdbc:mysql://localhost:3306/takeaway?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# mybatis configuration and xml mapping
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# pagination
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost
